const CARD_WIDTH = 290;
const CARD_HEIGHT = 160;
const CACHE_DURATION_SECONDS = 72000;
const LANG_ITEM_COUNT = 6;
const DIVIDER_Y = 44;
const ERROR_DIVIDER_Y = 84;

module.exports = { CARD_WIDTH, CARD_HEIGHT, CACHE_DURATION_SECONDS, LANG_ITEM_COUNT, DIVIDER_Y, ERROR_DIVIDER_Y };
